version: '3.7'

#
# docker compose up -d book_reviews
#

services:

  mongo:
    image: mongo

  mongo_express:
    image: mongo-express
    depends_on:
      - mongo

  book_reviews:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      MONGODB_URI: mongodb://mongo/node_mongo_book_reviews
    command: npm start
    depends_on:
      - mongo

  test_server:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      MONGODB_URI: mongodb://mongo/node_mongo_book_reviews_test
      JWT_SECRET: thisIsANotSoSecretTestSecretinDocker
    ports:
      - "3001:3000"
    command: npm start
    depends_on:
      - mongo
