#
# docker compose up -d book_reviews
#

services:

  mongo:
    image: mongo
    volumes:
      - "mongo_data:/data/db"

  mongo_express:
    image: mongo-express
    depends_on:
      - mongo

  book_reviews:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      MONGODB_URI: mongodb://mongo/node_mongo_book_reviews
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    command: npm start
    depends_on:
      - mongo
      - zipkin

  test_server:
    image: node:alpine
    working_dir: /home/node/app
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    environment:
      MONGODB_URI: mongodb://mongo/node_mongo_book_reviews_test
      OPEN_TELEMETRY_SERVICE_NAME: node_mongo_book_reviews_test
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
      JWT_SECRET: thisIsANotSoSecretTestSecretinDocker
    command: npm start
    depends_on:
      - mongo
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    expose:
      - 9411

volumes:

  mongo_data:
    driver: local
