version: '3.7'

#
# docker-compose up -d
#

services:

  mongo_express:
    ports:
      - "8081:8081"

  book_reviews:
    environment:
      - JWT_SECRET=thisIsSecretinDocker
    ports:
      - "3000:3000"
