version: '3.7'

#
# docker compose up -d book_reviews
#

services:

  mongo_express:
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: abcd1234

  book_reviews:
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: thisIsSecretInDocker
