require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BooksController, type: :controller do

  let(:book_name) { "name #{rand 1_000...10_000}" }

  # This should return the minimal set of attributes required to create a valid
  # Book. As you add validations to Book, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
        name: book_name
    }
  end

  let(:invalid_attributes) do
    {
        foo: "bar"
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let!(:user) do
    user = User.create email: "email-#{rand 1_000...10_000}@test.com"
    user.password = "password #{rand 1_000...10_000}"
    user.save!
    return user
  end

  let(:jwt_token) { Knock::AuthToken.new(payload: { sub: user.id }).token }
  let(:auth_header) { { 'Authorization': "Bearer #{jwt_token}" } }

  # I think this version of RSpec does not handle headers passed to #get or #post
  # So, we cannot use:
  #     post :create, params: {book: valid_attributes}, session: valid_session, headers: auth_header
  # We have to inject a valid token into the controller directly.  Yuck!
  before(:example) do
    def @controller.token_from_request_headers
      Knock::AuthToken.new(payload: { sub: User.all.first.id }).token
    end
  end

  describe "GET #index" do
    it "returns a success response" do
      book = Book.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      book = Book.create! valid_attributes
      get :show, params: {id: book.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Book" do
        expect do
          post :create, params: {book: valid_attributes}, session: valid_session
        end.to change(Book, :count).by(1)
      end

      it "renders a JSON response with the new book" do

        post :create, params: {book: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.media_type).to eq('application/json')
        expect(response.location).to eq(book_url(Book.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new book" do

        post :create, params: {book: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.media_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let (:expected_publisher) { "publisher #{rand 1_000...10_000}" }
      let(:new_attributes) do
        {
            publisher: expected_publisher
        }
      end

      it "updates the requested book" do
        book = Book.create! valid_attributes
        put :update, params: {id: book.to_param, book: new_attributes}, session: valid_session
        book.reload
        expect(book.publisher).to eq(expected_publisher)
      end

      it "renders a JSON response with the book" do
        book = Book.create! valid_attributes

        put :update, params: {id: book.to_param, book: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.media_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the book" do
        # skip("Figure out what invalid parameters to PUT would look like")
        Book.create! name: book_name
        book = Book.create! name: book_name.succ

        put :update, params: {id: book.to_param, book: {name: book_name}}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.media_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested book" do
      book = Book.create! valid_attributes
      expect do
        delete :destroy, params: {id: book.to_param}, session: valid_session
      end.to change(Book, :count).by(-1)
    end
  end

end
