#
# docker compose up -d
#

services:

  mongo:
    ports:
      - "27017:27017"

  mongo_express:
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: abcd1234
