#
# docker compose up -d
#

services:

  mongo:
    image: mongo
    volumes:
      - "mongo_data:/data/db"

  mongo_express:
    image: mongo-express
    depends_on:
      - mongo

volumes:

  mongo_data:
    driver: local
