#
# docker compose --file docker-compose.local.yml --file docker-compose.override.yml --file docker-compose.kafka-override.yml up -d kafka
#

services:

  kafka:
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092

  zipkin:
    ports:
      - 9411:9411
