version: '3.7'

#
# docker compose --file docker-compose.local.yml --file docker-compose.override.yml up -d
#

services:

  books:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start --workspace books
    deploy:
      replicas: 4
    depends_on:
      - kafka

  reviews:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start --workspace reviews
    deploy:
      replicas: 4
    depends_on:
      - kafka

  users:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start --workspace users
    deploy:
      replicas: 4
    depends_on:
      - kafka

  search:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start --workspace search
    deploy:
      replicas: 4
    depends_on:
      - kafka

  signatures:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - PORT=80
    command: npm start --workspace signatures
    deploy:
      replicas: 4

  jwts:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start --workspace jwts
    deploy:
      replicas: 4
    depends_on:
      - kafka

  gateway:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - PORT=80
      - BOOKS_SERVICE=http://books
      - REVIEWS_SERVICE=http://reviews
      - USERS_SERVICE=http://users
      - SEARCH_SERVICE=http://search
      - SIGNATURES_SERVICE=http://signatures
      - JWTS_SERVICE=http://jwts
    command: npm start --workspace gateway
    depends_on:
      - books
      - reviews
      - users
      - search
      - signatures
      - jwts

  kafka:
    image: bitnami/kafka:latest
    expose:
      - 9092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_NUM_PARTITIONS: 4
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 1

volumes:

  kafka_data:
    driver: local
