version: '3.7'

#
# docker compose --file docker-compose.containers.yml --file docker-compose.override.yml up -d
#

services:

  books:
    image: jeantessier/book_reviews-node_graphql_federation-books
    build: ./books
    volumes:
      - ./kafka:/home/node/kafka:ro
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  reviews:
    image: jeantessier/book_reviews-node_graphql_federation-reviews
    build: ./reviews
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  users:
    image: jeantessier/book_reviews-node_graphql_federation-users
    build: ./users
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  search:
    image: jeantessier/book_reviews-node_graphql_federation-search
    build: ./search
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  signatures:
    image: jeantessier/book_reviews-node_graphql_federation-signatures
    build: ./signatures
    deploy:
      replicas: 4

  jwts:
    image: jeantessier/book_reviews-node_graphql_federation-jwts
    build: ./jwts
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  gateway:
    image: jeantessier/book_reviews-node_graphql_federation-gateway
    build: ./gateway
    depends_on:
      - books
      - reviews
      - users
      - search
      - signatures
      - jwts

  kafka:
    image: bitnami/kafka:latest
    expose:
      - 9092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_NUM_PARTITIONS: 4
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 1

volumes:

  kafka_data:
    driver: local
