version: '3.7'

#
# docker compose --file docker-compose.yml --file docker-compose.override.yml up -d
#

services:

  books:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./books:/home/node/app
    environment:
      - PORT=80
    command: npm start
#    deploy:
#      replicas: 4
    depends_on:
      - kafka

  reviews:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./reviews:/home/node/app
    environment:
      - PORT=80
    command: npm start
#    deploy:
#      replicas: 4
    depends_on:
      - kafka

  users:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./users:/home/node/app
    environment:
      - PORT=80
    command: npm start
#    deploy:
#      replicas: 4
    depends_on:
      - kafka

  search:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./search:/home/node/app
    environment:
      - PORT=80
    command: npm start
#    deploy:
#      replicas: 4
    depends_on:
      - kafka

  signatures:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./signatures:/home/node/app
    environment:
      - PORT=80
    command: npm start
#    deploy:
#      replicas: 4
    depends_on:
      - kafka

  gateway:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./gateway:/home/node/app
    environment:
      - PORT=80
      - BOOKS_SERVICE=http://books
      - REVIEWS_SERVICE=http://reviews
      - USERS_SERVICE=http://users
      - SEARCH_SERVICE=http://search
      - SIGNATURES_SERVICE=http://signatures
    command: npm start
    depends_on:
      - books
      - reviews
      - users
      - search
      - signatures

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      replicas: 4
    depends_on:
      - zookeeper
