#
# docker compose --file docker-compose.containers.yml --file docker-compose.override.yml up -d
#

services:

  books:
    image: jeantessier/book_reviews-node_graphql_federation-books
    build: ./books
    volumes:
      - ./kafka:/home/node/kafka:ro
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - kafka
      - zipkin

  reviews:
    image: jeantessier/book_reviews-node_graphql_federation-reviews
    build: ./reviews
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - kafka
      - zipkin

  users:
    image: jeantessier/book_reviews-node_graphql_federation-users
    build: ./users
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - kafka
      - zipkin

  search:
    image: jeantessier/book_reviews-node_graphql_federation-search
    build: ./search
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - kafka
      - zipkin

  signatures:
    image: jeantessier/book_reviews-node_graphql_federation-signatures
    build: ./signatures
    environment:
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - zipkin

  jwts:
    image: jeantessier/book_reviews-node_graphql_federation-jwts
    build: ./jwts
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    deploy:
      replicas: 4
    depends_on:
      - kafka
      - zipkin

  gateway:
    image: jeantessier/book_reviews-node_graphql_federation-gateway
    build: ./gateway
    environment:
      ZIPKIN_EXPORTER_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - books
      - reviews
      - users
      - search
      - signatures
      - jwts

  kafka:
    image: apache/kafka:latest
    expose:
      - 9092
    volumes:
      - "kafka_data:/var/lib/kafka/data"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_LOG_RETENTION_HOURS: -1

  zipkin:
    image: openzipkin/zipkin
    expose:
      - 9411

volumes:

  kafka_data:
    driver: local
