version: '3.7'

#
# docker compose up -d
#
# or
#
# docker compose --file docker-compose.containers.yml --file docker-compose.override.yml up -d
#

services:

  books:
    environment:
      - JWT_SECRET=thisIsSecret

  reviews:
    environment:
      - JWT_SECRET=thisIsSecret

  users:
    environment:
      - JWT_SECRET=thisIsSecret

  search:
    environment:
      - JWT_SECRET=thisIsSecret

  jwts:
    environment:
      - JWT_SECRET=thisIsSecret

  gateway:
    ports:
      - 4000:80
