version: '3.7'

#
# docker compose --file docker-compose.containers.yml --file docker-compose.override.yml up -d
#

services:

  books:
    image: book-reviews/node_graphql_federation/books
    build: ./books
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  reviews:
    image: book-reviews/node_graphql_federation/reviews
    build: ./reviews
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  users:
    image: book-reviews/node_graphql_federation/users
    build: ./users
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  search:
    image: book-reviews/node_graphql_federation/search
    build: ./search
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  signatures:
    image: book-reviews/node_graphql_federation/signatures
    build: ./signatures
    deploy:
      replicas: 4

  jwts:
    image: book-reviews/node_graphql_federation/jwts
    build: ./jwts
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    deploy:
      replicas: 4
    depends_on:
      - kafka

  gateway:
    image: book-reviews/node_graphql_federation/gateway
    build: ./gateway
    depends_on:
      - books
      - reviews
      - users
      - search
      - signatures
      - jwts

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: 1000
      KAFKA_CREATE_TOPICS: book-reviews.books:4:1,book-reviews.reviews:4:1,book-reviews.users:4:1,book-reviews.searches:4:1
      KAFKA_LOG_RETENTION_MS: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    deploy:
#      replicas: 4 # We cannot do multiple brokers because of collisions on KAFKA_ADVERTISED_HOST_NAME
    depends_on:
      - zookeeper
