version: '3.7'

#
# docker compose up -d
#

services:

  books:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./books:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start
    deploy:
      replicas: 4
    depends_on:
      - kafka

  reviews:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./reviews:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start
    deploy:
      replicas: 4
    depends_on:
      - kafka

  users:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./users:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start
    deploy:
      replicas: 4
    depends_on:
      - kafka

  search:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./search:/home/node/app
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - PORT=80
    command: npm start
    deploy:
      replicas: 4
    depends_on:
      - kafka

  signatures:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./signatures:/home/node/app
    environment:
      - PORT=80
    command: npm start
    deploy:
      replicas: 4

  jwts:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./jwts:/home/node/app
    environment:
      - PORT=80
    command: npm start
    deploy:
      replicas: 4

  gateway:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./gateway:/home/node/app
    environment:
      - PORT=80
      - BOOKS_SERVICE=http://books
      - REVIEWS_SERVICE=http://reviews
      - USERS_SERVICE=http://users
      - SEARCH_SERVICE=http://search
      - SIGNATURES_SERVICE=http://signatures
      - JWTS_SERVICE=http://jwts
    command: npm start
    depends_on:
      - books
      - reviews
      - users
      - search
      - signatures
      - jwts

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: 1000
      KAFKA_CREATE_TOPICS: book-reviews.books:4:1,book-reviews.reviews:4:1,book-reviews.users:4:1,book-reviews.searches:4:1
      KAFKA_LOG_RETENTION_MS: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    deploy:
#      replicas: 4 # We cannot do multiple brokers because of collisions on KAFKA_ADVERTISED_HOST_NAME
    depends_on:
      - zookeeper
