version: '3.7'

#
# docker compose up -d
#

services:

  books:
    environment:
      - JWT_SECRET=thisIsSecret

  reviews:
    environment:
      - JWT_SECRET=thisIsSecret

  users:
    environment:
      - JWT_SECRET=thisIsSecret

  search:
    environment:
      - JWT_SECRET=thisIsSecret

  jwts:
    environment:
      - JWT_SECRET=thisIsSecret

  gateway:
    ports:
      - 4000:80
