#
# docker compose up -d
#

services:

  kafka:
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093

  zipkin:
    ports:
      - "9411:9411"
